# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f843f338e8ab1e8ea7d0255cc49b8ae677ddebe508c5a2eaff0687497708f2f244c3f8bf8689c6a5038248cfe2b361f8287f6169fc1610dda488be8b2c35e3

test:
  secret_key_base: a1f91d3785e110108ce6083339dac9d19d6e6560ae76e6857b2dd6786b79bc93fbee330fb244500c07dd179c730fb6536bbb62a5bcd8c99d1af852574ad9f425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
